- README.md
- cocoapods/foxSdk.podspec
> CocoaPods対応

- README.md
- cocoapods/foxSdk.podspec
1. 新しいAPIの説明: cacheDefaultUserAgent
2. podspec 更新
> v2.15.2gへバージョンアップ

- cocoapods/foxSdk.podspec
SystemConfiguration 削除
weak_framework SafariServices, AdSupport 追加
> v2.16gバージョンアップ

- cocoapods/foxSdk.podspec
1. zipファイル名が自動化ツールで出力したファイル名に合わせるための修正
2. バージョンアップ v2.16.1g
> version up v2.16.1g

- cocoapods/foxSdk.podspec
> version up to v2.16.2g

- cocoapods/foxSdk.podspec
- cocoapods/foxSdk.tvos.podspec
__for iOS__
push support version iOS 6.0
require AdSupport.framework
__for tvOS__
new support for tvOS 9.0
> push version 3.0.0

- cocoapods/foxSdk.podspec
push support version to iOS 7
add required framework SystemConfiguration
> update for 3.0.0

- lang/ja/README.md
- lang/zh-tw/README.md
done for Japanese & zh_tw
wait for ko
> add swift imports

- 4.x/lang/ja/README.md
- 4.x/lang/ja/doc/update/README.md
- CYZFox/4.0.0/CYZFox.podspec
- CYZFoxDy/4.0.0/CYZFoxDy.podspec
- CYZFoxEx/1.0.0/CYZFoxEx.podspec
- CYZFoxExDy/1.0.0/CYZFoxExDy.podspec
- CYZFoxTv/4.0.0/CYZFoxTv.podspec
- CYZFoxTvDy/4.0.0/CYZFoxTvDy.podspec
update module name FOXSDK => CYZFox
> [4.0.0] 20160902 4.0.0rc1

- 4.x/lang/ja/README.md
> Dev fox 4.0.0

- CYZFoxExt/1.0.0/CYZFoxExt.podspec
- CYZFoxExtDy/1.0.0/CYZFoxExtDy.podspec
> [4.0.0] 20160905 4.0.0rc2

- lang/ja/doc/fox_engagement/ViewTransactionEvent.md
- lang/zh-tw/doc/fox_engagement/ViewTransactionEvent.md
Fix parameter for tracking transaction event.
> Fix parameter for purchase event tracking

- CYZFox/3.6.0/CYZFox.podspec
- CYZFoxTv/3.6.0/CYZFoxTv.podspec
> [3.6.0] add cocoapods for 3.6.0

- lang/ja/doc/send_conversion/README.md
description of new API: `setInstallTrackingCompletionHandler:`
> [3.6.0] add description of setInstallTrackingCompletionHandler

- lang/ja/README.md
- lang/ja/doc/deferred_deeplink/README.md
- lang/ja/doc/optout/README.md
- lang/ja/doc/sdk_api/README.md
- lang/ja/doc/track_events/README.md
- lang/ja/doc/track_install/README.md
1. add doc of deferred deeplink implementation
2. add new API trackingCompletionHandler while deprecated onTrackFinish
3. update sample source to Swift3
> [4.1.0] doc update

- CYZFox/4.1.0/CYZFox.podspec
- CYZFoxDy/4.1.0/CYZFoxDy.podspec
> [4.1.0] may need WebKit in build settings

- lang/ja/doc/update/README.md
fix links & invalid method names
> [4.1.1] fix doc

- lang/en/doc/deferred_deeplink/README.md
- lang/en/doc/send_conversion/README.md
- lang/ja/doc/deferred_deeplink/README.md
- lang/ja/doc/send_conversion/README.md
1. update sample code
2. declare the thread where the handlers run
> [3.6.1] Update doc about deferred deep link handler

- lang/ja/doc/sdk_api/README.md
introduction about new APIs of set buid in re-engagement & get xuniqId
> [4.2.0] docment of new apis

- CYZFox/4.2.1/CYZFox.podspec
- CYZFoxDy/4.2.1/CYZFoxDy.podspec
- CYZFoxTv/4.2.1/CYZFoxTv.podspec
- CYZFoxTvDy/4.2.1/CYZFoxTvDy.podspec
> [4.2.1] CocoaPods for 4.2.1
